### ISSUE TITLE
No relative url in the [button] markup

### ISSUE THREAD

**Issue by oswaldderiemaecker** [clawfire/lean-template#2]
`[row][column][button href="/reducing-time-to-market/" title="Taking too long to market" color="blue" size="medium"]I am taking too long to Market[/button]`

`<a href="" title="Taking too long to market" class="ui blue medium button">I am taking too long to Market</a>`

**Comment by clawfire** [comment]
That's weird because I tested with : 

```
[button href="/consequatur-assumenda-nesciunt-nobis-nesciunt-magnam/" title="Discover our service" color="blue" size="medium"]See more[/button]
```

And it generate

``` html
<a href="/consequatur-assumenda-nesciunt-nobis-nesciunt-magnam/" title="Discover our service" class="ui blue medium button">See more</a>
```

**Comment by clawfire** [comment]
I'de also checked the generation code, there's no sanitizing process that may lead to a bug (maybe it's missing some to be really secure in case of admin access compromission to prevent injection but that's it)

**Comment by oswaldderiemaecker** [comment]
In the page I got:

[row][column][button href="/reducing-time-to-market/" title="Taking too long to market" color="blue" size="medium"]I am taking too long to Market[/button]

On the site I got:
<a href="" title="Taking too long to market" class="ui blue medium button">I am taking too long to Market</a>

logged or not.

**Comment by clawfire** [comment]
I see this on your site ... Can you confirm me you have the latest available version ?

**Comment by oswaldderiemaecker** [comment]
I confirm, I just updated it again now, still the same issue.

**Comment by oswaldderiemaecker** [comment]
Editing with the text editor, there is span injected in the url, not good but I can live with it.
[/column][column][button href="/<span id="sample-permalink"><span id="editable-post-name">reducing-time-to-market</span>/"</span> title="Taking too long to market" color="blue" size="medium"]Taking too long to market?[/button]

**Comment by clawfire** [comment]
Can I get access to your wordpress to check ?
